### ISSUE TITLE
Character convertion on INSERT

### ISSUE THREAD

**Issue by constantinje** [jchristn/DatabaseWrapper#9]
I have a problem using the pgsql wrapper.
When I use the Insert method with a string containing some character like 'é','è' ,'à'... there are converted as unicode (\u) and then I have an error: There's no column named '\u'

Is this possible to have a fix to keep the characters as they are ?

Using the query method everything is fine.

Best regards

**Comment by jchristn** [comment]
So it appears the issue is in ```Helper.IsExtendedCharacters``` which checks to see if a character exists that is greater than ASCII 128.  I just tested with PostgreSQL after changing this to 255 and it works, but need to check to see if it creates an issue for the other database types.  Will report back soon.

**Comment by jchristn** [comment]
Just fixed in v3.3.2.3 ([NuGet](https://www.nuget.org/packages/DatabaseWrapper.Postgresql/), [commit](https://github.com/jchristn/DatabaseWrapper/commit/34baf5112fa60c2d87e8be685ce50bc0ea1916d9)) - could you let me know if this resolves it for you?  Thanks for bringing this up!

**Comment by constantinje** [comment]
Unfortunately it's not fully resolved.
Now I have the string $JU$ added at the start and at the end of my strings in the database

**Comment by constantinje** [comment]
Sorry, it was the sanatizer that added me this strings, I dont now why.
But it's another problem

Thank you for the job

**Comment by constantinje** [comment]
What about non-ascii or ascii > 255 character ?

**Comment by jchristn** [comment]
Those would be treated as Unicode values.
